[server]
maxUploadSize = 10
enableStaticServing = false
enableCORS = true
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false